name: Terraform Workspaces

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    env:
      environment: somethingdev12

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-west-1

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v1

    - name: Terraform Deploy
      # uses: hashicorp/terraform-github-actions/init@v0.4.0
      working-directory: aws_s3_bucket
      run: |
        terraform init
        terraform workspace new ${{ env.environment }}
        terraform workspace select ${{ env.environment }} && terraform plan
        terraform workspace select ${{ env.environment }} && terraform apply -auto-approve
